export const MAIN_DATA = 'MAIN_DATA';
export const GET_TOP_PROPDUCTS = "GET_TOP_PROPDUCTS"
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_ALL_PRICE_PRODUCTS = "GET_ALL_PRICE_PRODUCTS"